services:
  cockroach:
    image: cockroachdb/cockroach:v22.1.9
    restart: unless-stopped
    ports:
      - 8081:8080
      - 26257:26257
    command: start-single-node --insecure
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/"]
      interval: 20s
      timeout: 3s
      retries: 10
  migrate:
    image: migrate/migrate
    depends_on:
      - cockroach
    links:
      - cockroach
    volumes:
      - ./migrations:/migrations
    command: -path /migrations -database cockroachdb://root:@cockroach:26257/?sslmode=disable up 1
