version: "3"

dotenv:
  - .env

exclude:
  - volume

tasks:
  start:
    cmds:
      - go run ./cmd/server

  test:
    method: none
    sources:
      - "**/*.go"
    cmds:
      - go test -run {{default "''" .GO_TEST_FILTER}} {{.GO_TEST_FLAGS}} {{default "./..." .CLI_ARGS}}

  migrate:create:
    cmds:
      - migrate create -dir migrations -seq -ext sql {{.CLI_ARGS}}

  migrate:up:
    cmds:
      - migrate -path ./migrations -database {{.DATABASE_URL}} up

  migrate:down:
    cmds:
      - migrate -path ./migrations -database {{.DATABASE_URL}} down

  auth:login:
    cmds:
      - deno run --unstable -A cmd/deno/login.ts

  auth:signup:
    cmds:
      - deno run --unstable -A cmd/deno/signup.ts
