name: ci

on: [push, pull_request]

jobs:
  ci:
    name: continous integration
    if: |
      github.event_name == 'push' ||
      !startsWith(github.event.pull_request.head.label, 'falentio:')
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - run: docker compose up -d

      - name: download dependency
        run: go mod download

      - name: build
        run: go build ./...

      - name: run vet
        run: go vet ./...

      - name: run test
        run: go test -race -vet=off -covermode=atomic -coverprofile=coverage.out ./...
        env:
          DATABASE_URL: "postgres://root:@cockroach:26257/?sslmode=disable"

      - uses: codecov/codecov-action@v3
