name: ci

on: [push, pull_request]

jobs:
  ci:
    name: continous integration
    if: |
      github.event_name == 'push' ||
      !startsWith(github.event.pull_request.head.label, 'falentio:')
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: verify dependency
        run: go mod verify

      - name: build
        run: go build ./...

      - name: run vet
        run: go vet ./...

      - name: compose up
        uses: isbang/compose-action@v1.3.2
        with:
          compose-file: ./docker-compose.yml

      - name: run test
        run: go test -race -vet=off ./...
        env:
          DATABASE_URL: "postgres://root:@localhost:26257/"
